# Generated by Django 4.1.7 on 2023-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Rom', 'Romance'), ('Com', 'Comedy'), ('Dra', 'Drama'), ('Ani', 'Animation'), ('Fan', 'Fantasy'), ('Act', 'Action')], default=0, max_length=3),
            preserve_default=False,
        ),
    ]
